language: java
jdk:
  - openjdk15

script:
  - ./mvnw clean install -B

sudo: true

before_install: chmod +x mvnw

jobs:
  include:
    - stage: test
      script: ./mvnw clean test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: name-d
  on:
    main


